src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Interaction_Source__c</fullName>
        <description>The method by which the data is being added as an Interaction. Set to &quot;Manual Entry&quot; for hand entry, otherwise it represents the integration source (Webform, Purchase List, etc.) Also used in the Skip Mapping functionality on Interaction Mappings.</description>
        <label>Interaction Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual Entry</fullName>
                    <default>true</default>
                    <label>Manual Entry</label>
                </value>
                <value>
                    <fullName>Purchase List</fullName>
                </value>
                <value>
                    <fullName>Student Information System</fullName>
                </value>
                <value>
                    <fullName>Webform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction_Mapping__c.object
<CustomObject>
    <description>Used to map fields from source Object to target Object in the Interactions process.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>A checkbox to activate an Interaction Mapping record.</description>
        <inlineHelpText>If checked, the Interaction Mapping is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insert_Null__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for checkboxes to prevent unmapped checkboxes from being written over to false.</description>
        <inlineHelpText>Used for checkboxes to prevent unmapped checkboxes from being written over to false.</inlineHelpText>
        <label>Insert Null</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skip_Mapping__c</fullName>
        <description>Select the Interaction Sources that should ignore this mapping configuration. The values in this picklist should match the values in Interaction&apos;s &quot;Interaction Sources&quot; field.</description>
        <inlineHelpText>Select the Interaction Sources that should ignore this import configuration.</inlineHelpText>
        <label>Skip Mapping</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual Entry</fullName>
                </value>
                <value>
                    <fullName>Purchase List</fullName>
                </value>
                <value>
                    <fullName>Student Information System</fullName>
                </value>
                <value>
                    <fullName>Webform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Field_API_Name__c</fullName>
        <description>The field on the Target Object you would like to map an Interaction field value to. The value in this field must be in API format and match an existing field on the Target Object.</description>
        <inlineHelpText>The field on the Target Object you would like to map to. Ensure this is in API format and matches the existing field on the Target Object.</inlineHelpText>
        <label>Target Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_API_Name__c</fullName>
        <description>The API name of the Target Object to map Interaction data to. When adding new values, ensure that you use the API name of the object.</description>
        <inlineHelpText>Select the Target Object to map Interaction data to.</inlineHelpText>
        <label>Target Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CampaignMember</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>hed__Affiliation__c</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction Mapping</label>
    <nameField>
        <displayFormat>INTMap-{000000}</displayFormat>
        <label>Interaction Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/INT_InteractionMappingService.cls
/*****************************************
* File: INT_InteractionMappingService
* Author: Sierra-Cedar
* Description: Caches Interaction_Mapping__c records for reference during Interactions processing
******************************************/
public class INT_InteractionMappingService {
    private Map<String, Set<String>> skipMappingMap = new Map<String, Set<String>>();
    public Map<String, List<Interaction_Mapping__c>> intMappingMap = new Map<String, List<Interaction_Mapping__c>>();

    public INT_InteractionMappingService() {
        for (Interaction_Mapping__c mapping : [
            SELECT Skip_Mapping__c, Insert_Null__c, Target_Object_API_Name__c, Source_Field_API_Name__c,
                Target_Field_API_Name__c, Source_Object_API_Name__c
            FROM Interaction_Mapping__c
            WHERE Active__c = true
        ]) {
            if (!intMappingMap.containsKey(mapping.Target_Object_API_Name__c)) {
                intMappingMap.put(mapping.Target_Object_API_Name__c, new List<Interaction_Mapping__c>{mapping});
            } else {
                intMappingMap.get(mapping.Target_Object_API_Name__c).add(mapping);
            }

            // Populate excluded sources map
            if (!String.isEmpty(mapping.Skip_Mapping__c)) {
                skipMappingMap.put(mapping.Id, new Set<String>(mapping.Skip_Mapping__c.split(';')));
            }
        }
    }

    /**
     * @description Checks to see if field has an excluded source
     * @param mappingId, the Interaction_Mapping__c record Id to pull the record from the Map.
     * @param interactionSource, the value of the Interaction.Interaction_Source__c field.
     * @param skipOrPreserveSourcesMap, the Map containing the Skip Mapping
     * @return a Boolean determining whether or not the field is excluded or overwrite if blank.
     */
    private Boolean isSkipOrPreserveSourceField(
        String mappingId, String interactionSource, Map<String, Set<String>> skipOrPreserveSourcesMap
    ) {
        Set<String> sourcesToCheck = (skipOrPreserveSourcesMap.containsKey(mappingId)
            ? skipOrPreserveSourcesMap.get(mappingId) : new Set<String>());

        return sourcesToCheck.contains(interactionSource);
    }

    /**
     * @description Populates an SObject with Interaction data based on the mapping.
     * @param interaction, the Interaction Record to copy from.
     * @param theObject, the SObject to populate.
     * @return theObject, the SObject that data was applied to.
     */
    public SObject applyDataToSObject(Interaction__c interaction, SObject theObject) {
        String objectName = theObject.getSObjectType().getDescribe().getName();

        if (intMappingMap.containsKey(objectName)) {
            for (Interaction_Mapping__c mapping : intMappingMap.get(objectName)) {
                // Only copy the field value if the Interaction__c field value is different than the Object field value.
                if (isSkipOrPreserveSourceField(mapping.Id, interaction.Interaction_Source__c, skipMappingMap)) {
                    continue; // Prevent mapping of field if it's a skip field or a preserve target source
                } else if (mapping.Insert_Null__c
                    || (interaction.get(mapping.Source_Field_API_Name__c) != null
                        && interaction.get(mapping.Source_Field_API_Name__c) != '')
                ) {
                    theObject.put(mapping.Target_Field_API_Name__c, interaction.get(mapping.Source_Field_API_Name__c));
                }

            }
        }

        return theObject;
    }

    /**
     * @description Applies data from a source Object to the Interaction__c based upon Interaction_Mapping__c records.
     * @param theObject, the SObject to pull data from.
     * @param interaction, the Interaction__c record to populate.
     * @return interaction, the populated Interaction__c record.
     */
    public Interaction__c applyDataToInteraction(SObject theObject, Interaction__c interaction) {
        if (intMappingMap.containsKey('Interaction__c')) {
            for (Interaction_Mapping__c mapping : intMappingMap.get('Interaction__c')) {
                if (mapping.Source_Object_API_Name__c == theObject.getSObjectType().getDescribe().getName()) {
                    interaction.put(mapping.Target_Field_API_Name__c, theObject.get(mapping.Source_Field_API_Name__c));
                }
            }
        }

        return interaction;
    }
}