src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Source__c</fullName>
        <description>The method by which the data is being added as an Interaction. Set to &quot;Manual Entry&quot; for hand entry, otherwise it represents the integration source (Webform, Purchase List, etc.) Also used in the Skip Mapping functionality on Interaction Mappings.</description>
        <label>Interaction Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual Entry</fullName>
                    <default>true</default>
                    <label>Manual Entry</label>
                </value>
                <value>
                    <fullName>Purchase List</fullName>
                </value>
                <value>
                    <fullName>Student Information System</fullName>
                </value>
                <value>
                    <fullName>Webform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interaction_Status__c</fullName>
        <description>When set to &quot;New,&quot; the Interaction Processor runs, then updates the Status based on the result to &quot;Imported&quot; or &quot;Audit Needed.&quot;</description>
        <inlineHelpText>Set the Status to &quot;New&quot; and save to kick off the Interaction process.</inlineHelpText>
        <label>Interaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Audit Required</fullName>
                </value>
                <value>
                    <fullName>Imported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction_Mapping__c.object
<CustomObject>
    <description>Used to map fields from source Object to target Object in the Interactions process.</description>
    <label>Interaction Mapping</label>
    <nameField>
        <displayFormat>INTMap-{000000}</displayFormat>
        <label>Interaction Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/INT_InteractionMappingService_TEST.cls
/*****************************************
* File: INT_InteractionMappingService_TEST
* Author: Sierra-Cedar
* Description: Unit Tests for
******************************************/
@IsTest
private class INT_InteractionMappingService_TEST {
    @testSetup static void setUpTest() {
        // Create and insert Interaction Mapping Test Data
        List<Interaction_Mapping__c> testMappings = INT_TestDataFactory.createTestMappings();
        insert testMappings;
    }

    static testMethod void testCreateContact() {
        // Arrange
        Interaction__c testInteraction = new Interaction__c(
            First_Name__c = 'Test',
            Last_Name__c = 'Contact',
            Interaction_Status__c = 'New'
        );

        Contact c = new Contact(
            FirstName = 'Something',
            LastName = 'Else'
        );

        // Act
        Test.startTest();
        INT_InteractionMappingService interactionMapping = new INT_InteractionMappingService();
        interactionMapping.applyDataToSObject(testInteraction, c);
        Test.stopTest();

        // Assert
        System.assert(c.FirstName == 'Test');
        System.assert(c.LastName == 'Contact');
    }

    static testMethod void testCreateContactExcludedSources() {
        // Arrange
        Interaction__c testInteraction = new Interaction__c(
            First_Name__c = 'Test',
            Last_Name__c = 'Contact',
            Interaction_Status__c = 'New',
            Interaction_Source__c = 'Webform'
        );

        Contact c = new Contact(
            FirstName = 'Something',
            LastName = 'Else'
        );

        // Act
        Test.startTest();
        INT_InteractionMappingService interactionMapping = new INT_InteractionMappingService();
        interactionMapping.applyDataToSObject(testInteraction, c);
        Test.stopTest();

        // Assert
        // Interaction data should NOT be copied over since we exclude Webform Sources
       	System.assert(c.FirstName == 'Something');
       	System.assert(c.LastName == 'Else');
    }
}